# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='product name')),
                ('product_price', models.IntegerField(default=0, verbose_name='product price')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='datetime created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='datetime updated')),
                ('deleted_at', models.DateTimeField(default=None, verbose_name='datetime deleted')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='product name')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductCategory'),
        ),
    ]
